### ISSUE TITLE
rabin2: wrong results for imported symbols for /bin/vim on Fedora 25

### ISSUE THREAD

**Issue by armijnhemel** [radare/radare2#7086]
hi,

for /bin/vim on my Fedora 25 system the imported symbols are not extracted correctly. The version of vim is:

$ rpm -qfi /bin/vim
Name        : vim-enhanced
Epoch       : 2
Version     : 8.0.425
Release     : 1.fc25
Architecture: x86_64

$ sha256sum /bin/vim
9a7180dbee96b582bb41b9d2a44bfb9181b6561f8174b348c37ab7f66fee22ed  /bin/vim

$ file /bin/vim
/bin/vim: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=951455b0c009325fcd14cad30e850c25cb9ce6f9, stripped

All symbols that are imported are:

f sym.imp.socket 16 0x00000000

$ rabin2 -sr /bin/vim | grep sym.imp.socket | wc -l
210

radare2:

[0x00055a40]> fs imports
[0x00055a40]> f
0x00000000 16 sym.imp.socket
0x00000000 16 loc.imp.socket

Other binaries I tested with seem to work just fine,

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by armijnhemel** [comment]
Apologies, I knew I had forgotten something:

$ r2 -v
radare2 1.4.0-git 0 @ linux-x86-64 git.1.4.0-git
commit: HEAD build: 2017-03-21__13:06:09

**Comment by radare** [comment]
@alvarofe ^ i think its related to the changes in the import-plt resolution

**Comment by radare** [comment]
pls shre the bin

**Comment by armijnhemel** [comment]
[vim.zip](https://github.com/radare/radare2/files/859290/vim.zip)

Here you go (in a ZIP file). This is the standard binary from Fedora 25.

**Comment by alvarofe** [comment]
Thanks for sharing, I'll take a look

**Comment by alvarofe** [comment]
Check from master, it should be fixed now.

**Comment by armijnhemel** [comment]
Want to, but get a compilation error:

p/debug_native.c:490:24: error: too few arguments to function ‘r_debug_pid_new’
   r_list_append (list, r_debug_pid_new ("(current)", pid, 's', 0));
                        ^~~~~~~~~~~~~~~
In file included from p/debug_native.c:4:0:
/home/armijn/git/radare2/libr/include/r_debug.h:396:18: note: declared here
 R_API RDebugPid *r_debug_pid_new(const char *path, int pid, int uid, char status, ut64 pc);
                  ^~~~~~~~~~~~~~~
p/debug_native.c:499:12: warning: variable ‘gid’ set but not used [-Wunused-but-set-variable]
   int uid, gid;
            ^~~
p/debug_native.c:564:25: error: too few arguments to function ‘r_debug_pid_new’
    r_list_append (list, r_debug_pid_new (buf, i, 's', 0));
                         ^~~~~~~~~~~~~~~
In file included from p/debug_native.c:4:0:

**Comment by alvarofe** [comment]
unrelated with my commit at least

**Comment by armijnhemel** [comment]
Yeah, introduced by 94d85cad it seems (very recently).

**Comment by alvarofe** [comment]
try again, i fixed based on your reply i should compile in linux to maybe fix them all.

**Comment by armijnhemel** [comment]
latest master fixes the compilation bugs and I have verified that it indeed works now.

**Comment by alvarofe** [comment]
\o/
