### ISSUE TITLE
[PPC] infinte loop on `pdf`

### ISSUE THREAD

**Issue by wargio** [radare/radare2#8591]
```bash
[deroad@oto Downloads]$ r2 busybox-powerpc 
Warning: Cannot initialize dynamic strings
 -- Change the size of the file with the 'r' (resize) command
[0x100001f8]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x10000000 to 0x10119630
aav: from 0x10000000 to 0x10119630
aav: from 0x1012a000 to 0x1012a3e4
aav: from 0x1012a3e4 to 0x1012ec98
Value from 0x1012a3e4 to 0x1012ec98
aav: from 0x10000000 to 0x10119630
aav: from 0x1012a000 to 0x1012a3e4
aav: from 0x1012a3e4 to 0x1012ec98
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x100001f8]> pdf
```
EDIT:

the command that actually generates the problem is `pD 937332 @ 0x100001f8`

- Binary: https://github.com/radare/radare2-regressions/pull/1034

**Comment by wargio** [comment]
```
radare2 1.7.0-git 16199 @ linux-x86-64 git.1.6.0-938-g3adb70a75
commit: 3adb70a75307a6b4101ade64f7c0f48420422a93 build: 2017-09-26__12:58:49
```

**Comment by trufae** [comment]
do u know which commit broke that? u said last week was fine

**Comment by wargio** [comment]
i can search for it, but there are lots of commits between today and last week...

**Comment by XVilka** [comment]
@wargio use git bisect

**Comment by XVilka** [comment]
Please also push the test into r2-regressions for this case.

**Comment by mscherer** [comment]
I tried to reproduce it, and it is now fixed:
```
$ r2 bins/elf/busybox-powerpc
Warning: Cannot initialize dynamic strings
[0x100001f8]> pdf
p: Cannot find function at 0x100001f8
[0x100001f8]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x10000000 to 0x10119630
aav: from 0x10000000 to 0x10119630
aav: from 0x1012a000 to 0x1012a3e4
aav: from 0x1012a3e4 to 0x1012ec98
Value from 0x1012a3e4 to 0x1012ec98
aav: from 0x10000000 to 0x10119630
aav: from 0x1012a000 to 0x1012a3e4
aav: from 0x1012a3e4 to 0x1012ec98
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x100001f8]> pdf
Linear size differs too much from the bbsum, please use pdr instead.
```
