### ISSUE TITLE
Android NDK builds fail with "error: undefined reference to 'r_socket_connect_serial'"

### ISSUE THREAD

**Issue by dequis** [radare/radare2#7739]
Broken by 6c37a9aa10a8d2b180c798aeb5302e817d52ef2c and 752a1d6e2759477f79552b47667eba65f104ca47

```
ndk-gcc -fPIC -fPIE -o radare2 main.c rabin2.c radare2.c radiff2.c rafind2.c rahash2.c rarun2.c rasm2.c rax2.c ragg2.c -fPIC -fPIE -fPIC -fPIE -pie -fPIC -fPIE -I../../libr/include/ -I/home/dx/test/radare/radare2/libr/../shlr/spp -fPIC -fPIE -fPIC -fpic -fPIC -fpic   -g -Wall -D__UNIX__=1 -I/home/dx/test/radare/radare2/libr/../shlr/zip/include  -pie ../../libr/io/libr_io.a ../../libr/asm/libr_asm.a ../../libr/egg/libr_egg.a ../../libr/core/libr_core.a ../../libr/crypto/libr_crypto.a ../../libr/parse/libr_parse.a ../../libr/anal/libr_anal.a ../../libr/fs/libr_fs.a ../../libr/magic/libr_magic.a ../../libr/cons/libr_cons.a ../../libr/syscall/libr_syscall.a ../../libr/flag/libr_flag.a ../../libr/reg/libr_reg.a ../../libr/debug/libr_debug.a ../../libr/search/libr_search.a ../../libr/config/libr_config.a ../../libr/lang/libr_lang.a ../../libr/bp/libr_bp.a ../../libr/hash/libr_hash.a ../../libr/bin/libr_bin.a ../../libr/util/libr_util.a ../../libr/socket/libr_socket.a ../../shlr/grub/libgrubfs.a ../../shlr/capstone/libcapstone.a ../../shlr/sdb/src/libsdb.a ../../shlr/gdb/lib/libgdbr.a ../../shlr/wind/libr_wind.a ../../shlr/java/libr_java.a -lm  /home/dx/test/radare/radare2/libr/../shlr/zip/librz.a /home/dx/test/radare/radare2/libr/..//shlr/bochs/lib/libbochs.a /home/dx/test/radare/radare2/libr/..//shlr/qnx/lib/libqnxr.a
i686-linux-android-gcc -L/home/dx/ndk/android-ndk-r15/platforms/android-19/arch-x86/usr/lib --sysroot=/home/dx/ndk/android-ndk-r15/platforms/android-19/arch-x86 -fPIC -fPIE -fPIC -fPIE -pie -fPIC -fPIE -I../../libr/include/ -I/home/dx/test/radare/radare2/libr/../shlr/spp -fPIC -fPIE -fPIC -fpic -fPIC -fpic -g -Wall -D__UNIX__=1 -I/home/dx/test/radare/radare2/libr/../shlr/zip/include --sysroot=/home/dx/ndk/android-ndk-r15/platforms/android-19/arch-x86 -I/home/dx/ndk/android-ndk-r15/platforms/android-19/arch-x86/usr/include -fPIC -fPIE -fPIC -fPIE -o radare2 main.c rabin2.c radare2.c radiff2.c rafind2.c rahash2.c rarun2.c rasm2.c rax2.c ragg2.c -fPIC -fPIE -fPIC -fPIE -pie -fPIC -fPIE -I../../libr/include/ -I/home/dx/test/radare/radare2/libr/../shlr/spp -fPIC -fPIE -fPIC -fpic -fPIC -fpic -g -Wall -D__UNIX__=1 -I/home/dx/test/radare/radare2/libr/../shlr/zip/include -pie ../../libr/io/libr_io.a ../../libr/asm/libr_asm.a ../../libr/egg/libr_egg.a ../../libr/core/libr_core.a ../../libr/crypto/libr_crypto.a ../../libr/parse/libr_parse.a ../../libr/anal/libr_anal.a ../../libr/fs/libr_fs.a ../../libr/magic/libr_magic.a ../../libr/cons/libr_cons.a ../../libr/syscall/libr_syscall.a ../../libr/flag/libr_flag.a ../../libr/reg/libr_reg.a ../../libr/debug/libr_debug.a ../../libr/search/libr_search.a ../../libr/config/libr_config.a ../../libr/lang/libr_lang.a ../../libr/bp/libr_bp.a ../../libr/hash/libr_hash.a ../../libr/bin/libr_bin.a ../../libr/util/libr_util.a ../../libr/socket/libr_socket.a ../../shlr/grub/libgrubfs.a ../../shlr/capstone/libcapstone.a ../../shlr/sdb/src/libsdb.a ../../shlr/gdb/lib/libgdbr.a ../../shlr/wind/libr_wind.a ../../shlr/java/libr_java.a -lm /home/dx/test/radare/radare2/libr/../shlr/zip/librz.a /home/dx/test/radare/radare2/libr/..//shlr/bochs/lib/libbochs.a /home/dx/test/radare/radare2/libr/..//shlr/qnx/lib/libqnxr.a
src/gdbclient/core.c:71: error: undefined reference to 'r_socket_connect_serial'
collect2: error: ld returned 1 exit status
make: *** [Makefile:115: build] Error 1
```

This error only appears for static builds, which seem to be all of them anyway (there's a `STATIC_BUILD=1` in `android-build.sh` forcing it for everything, it works if that's removed)

**Comment by radare** [comment]
fixed
