### ISSUE TITLE
REGRESSION: undefined reference to `shm_open'

### ISSUE THREAD

**Issue by Grazfather** [radare/radare2#15048]
This is caused by commit 43c61fccbdd0ac6ac2af40dd2106ea97f7db4607

See [this](https://cloud.docker.com/repository/registry-1.docker.io/grazfather/pwndock/builds/2b2c9adb-2ccf-47a4-8188-30adf729b3c3) build failure, with a dockerfile with which you can reproduce the issue.

### Work environment

Above dockerfile
### Expected behavior
Build succeeds
### Actual behavior
```bash
/root/tools/radare2/libr/io/libr_io.so: undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
../rules.mk:78: recipe for target 'rax2' failed
make[2]: *** [rax2] Error 1
Makefile:14: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
```
### Steps to reproduce the behavior 
Use above dockerfile and run:
```bash
git co 43c61fccbdd0ac6ac2af40dd2106ea97f7db4607
./sys/install.sh
```

**Comment by radare** [comment]
fixing it was easier than reporting the issue

**Comment by Grazfather** [comment]
Testing your code properly before merging would have been better than breaking people's builds, but here we are.

**Comment by radare** [comment]
Indeed.
